version: "3"
services:
        web:
                image: nginx
                volumes:
                        - ./src:/usr/share/nginx/html
                        - ./redzicleon.conf:/etc/nginx/conf.d/default.conf
                ports:
                        - "80:80"
