version: "3.3"
services:
        web:
                image: nginx
                volumes:
                        - ${PWD}/src:/usr/share/nginx/html
                        - type: volume
                          source: nginx_conf/nginx.conf
                          target: /etc/nginx/nginx.conf
                          read_only: true
                ports:
                        - "80:80"
volumes:
        nginx_conf:
